/**
 * Minimal stub for @tamagui/lucide-icons in Vitest/Node.js environments.
 * The real implementation uses react-native-svg for native and SVG for web.
 */
export const ChevronLeft = () => null
export const ChevronRight = () => null
export const ChevronUp = () => null
export const ChevronDown = () => null
export const X = () => null
export const Check = () => null
export const Plus = () => null
export const Minus = () => null
export const Menu = () => null
export const Search = () => null
export const Settings = () => null
export const User = () => null
export const Home = () => null
export const Eye = () => null
export const EyeOff = () => null
export const Lock = () => null
export const Unlock = () => null
export const Trash = () => null
export const Trash2 = () => null
export const Edit = () => null
export const Edit2 = () => null
export const Edit3 = () => null
export const Save = () => null
export const Copy = () => null
export const Share = () => null
export const Share2 = () => null
export const ArrowLeft = () => null
export const ArrowRight = () => null
export const ArrowUp = () => null
export const ArrowDown = () => null
export const Info = () => null
export const AlertCircle = () => null
export const AlertTriangle = () => null
export const HelpCircle = () => null
export const Star = () => null
export const Heart = () => null
export const Bookmark = () => null
export const Clock = () => null
export const Calendar = () => null
export const Mail = () => null
export const Phone = () => null
export const Camera = () => null
export const Image = () => null
export const File = () => null
export const Folder = () => null
export const Download = () => null
export const Upload = () => null
export const Link = () => null
export const ExternalLink = () => null
export const LogIn = () => null
export const LogOut = () => null
export const RefreshCw = () => null
export const MoreHorizontal = () => null
export const MoreVertical = () => null
export const Grid = () => null
export const List = () => null
export const Sun = () => null
export const Moon = () => null
export const Zap = () => null
export const Activity = () => null
export const Layers = () => null
export const Map = () => null
export const Globe = () => null
export const Wifi = () => null
export const Battery = () => null
export const Volume = () => null
export const Volume2 = () => null
export const VolumeX = () => null
export const Play = () => null
export const Pause = () => null
export const Stop = () => null
export const SkipBack = () => null
export const SkipForward = () => null
export const Rewind = () => null
export const FastForward = () => null
